services:
  - type: web
    name: telegram-bot
    env: python
    plan: free    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HOST
        value: 0.0.0.0
      - key: WEBHOOK_URL
        sync: false # Se configurará manualmente en el dashboard
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
    autoDeploy: true
