services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    region: ohio  # Puedes cambiar la región si deseas    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HOST
        value: 0.0.0.0
      - key: WEBHOOK_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
